import type { Metadata } from "next";
import { SansFont, SerifFont, MonoFont } from "@/lib/fonts";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SansFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
